### ISSUE TITLE
CI/CD 세팅

### ISSUE THREAD

**Issue by oyune** [Team-Resuscitation/instagram-Server#5]
# CI/CD 세팅
1. aws 세팅
2. 깃허브 액션 작성

**Comment by cmsong111** [comment]
1. AWS EC2 에서 환경변수 세팅 완료
  1. RDS 연결 완료
2. 깃허브 액션
  1. gradle-build-action을 이용한 Jar 빌드 완료
  2. AWS 인바운드 연결 보안 규칙 추가/삭제 완료
  3. appleboy/scp-action을 이용한 Jar 파일 전송 구현 완료
  4. appleboy/ssh-action을 이용한 기존 Spring 프로세스 종료 & nohup을 이용한 백그라운드 서비스 실행 구현완료
